apiVersion: 1
groups:
    - orgId: 1
      name: Evaluation group
      folder: Alerts/Error alerts
      interval: 30s
      rules:
        - uid: aeg2o4x5xg1dsb
          title: HTTP client errors alert
          condition: error_count_threshold
          data:
            - refId: error_count
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: P1809F7CD0C75ACF3
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: P1809F7CD0C75ACF3
                editorMode: code
                exemplar: false
                expr: |-
                    round(
                        sum(
                            label_replace(
                                sum(increase(http_server_requests_total{code=~"4.."}[1m])) by (code)
                                    or on() vector(0),
                                "error_category",
                                "4xx - Client error",
                                "code",
                                ".*"
                            )
                        ) by (error_category),
                        0.01
                    )
                instant: true
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: error_count
            - refId: error_count_threshold
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 100
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: error_count
                intervalMs: 1000
                maxDataPoints: 43200
                refId: error_count_threshold
                type: threshold
          dashboardUid: minitwit_dashboard
          panelId: 2
          noDataState: NoData
          execErrState: Error
          annotations:
            __dashboardUid__: minitwit_dashboard
            __panelId__: "2"
            summary: 'The number of client-side errors for the last minute has exceeded the threshold (acceptable: <100, actual: {{ $values.error_count }}).'
          labels: {}
          isPaused: false
        - uid: deg3mpw8ilxq8d
          title: HTTP server errors alert
          condition: error_count_threshold
          data:
            - refId: error_count
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: P1809F7CD0C75ACF3
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: P1809F7CD0C75ACF3
                editorMode: code
                exemplar: false
                expr: |-
                    round(
                        sum(
                            label_replace(
                                sum(increase(http_server_requests_total{code=~"5.."}[1m])) by (code)
                                    or on() vector(0),
                                "error_category",
                                "5xx - Server error",
                                "code",
                                ".*"
                            )
                        ) by (error_category),
                        0.01
                    )
                instant: true
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: error_count
            - refId: error_count_threshold
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 10
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: error_count
                intervalMs: 1000
                maxDataPoints: 43200
                refId: error_count_threshold
                type: threshold
          dashboardUid: minitwit_dashboard
          panelId: 2
          noDataState: NoData
          execErrState: Error
          annotations:
            __dashboardUid__: minitwit_dashboard
            __panelId__: "2"
            summary: 'The number of server-side errors for the last minute has exceeded the threshold (acceptable: <10, actual: {{ $values.error_count }}).'
          isPaused: false