# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"  # Adjust if your docker-compose.yml is in a subdirectory
    schedule:
      interval: "daily"  # Can be daily, weekly, or monthly
    commit-message:
      prefix: "[Dependabot] Docker Update"
    labels:
      - "dependencies"
      - "docker"
    ignore:
      - dependency-name: "nginx"
        versions: ["1.23.0"]  # Example of ignoring a specific update
