services:
  web:
    build: .
    container_name: minitwit
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: minitwit
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "4567:4567"
    networks:
      - minitwit_network

  db:
    image: postgres:15
    container_name: minitwit_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minitwit
    ports:
      - "5432:5432"
    networks:
      - minitwit_network
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

networks:
  minitwit_network:
    driver: bridge

volumes:
  pg_data:
