version: '3.8' # version to be compatible with docker swarm/stack deployments

services:
  test:
    image: ruby:3.3
    container_name: minitwit_test
    volumes:
      - .:/app # Mount your project directory into the container
    working_dir: /app
    env_file:
      - .env.test
    entrypoint: ["/bin/bash", "-c", "bundle install && rspec"]
    depends_on:
      - db
    networks:
      - minitwit_network_test

  db:
    image: postgres:15
    container_name: minitwit_test_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minitwit
    expose:
      - "5432"
    networks:
      - minitwit_network_test
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  minitwit_network_test:
    driver: bridge

volumes:
  pg_data:
