services:
  dev:
    image: ruby:3.3
    container_name: minitwit_dev
    volumes:
      - .:/app # Mount your project directory into the container
    working_dir: /app
    entrypoint: ["/bin/bash", "-c", "bundle install && /bin/bash"]
    depends_on:
      - db
    networks:
      - minitwit_network_dev
    ports:
      - "4567:4567" # Exposing the default Sinatra port, adjust as needed
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: minitwit_dev_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minitwit
    ports:
      - "5432:5432"
    networks:
      - minitwit_network_dev
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - minitwit_network_dev

  grafana:
    image: grafana/grafana:11.5.2
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/predefined-dashboards:/predefined-dashboards
    ports:
      - "3000:3000"  
    networks:
      - minitwit_network_dev

networks:
  minitwit_network_dev:
    driver: bridge

volumes:
  pg_data:
  grafana-data:
