services:
  web:
    image: registry.digitalocean.com/sad-containers/minitwit:${TAG}
    container_name: minitwit
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4567:4567"
    networks:
      - minitwit_network
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: minitwit_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minitwit
    expose:
      - "5432"
    networks:
      - minitwit_network
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  minitwit_network:
    driver: bridge

volumes:
  pg_data:
