services:
  web:
    build: .
    container_name: minitwit
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4567:4567"
    networks:
      - minitwit_network
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: minitwit_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minitwit
    expose:
      - "5432"
    networks:
      - minitwit_network
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.prod.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    networks:
      - minitwit_network

  grafana:
    image: grafana/grafana:11.5.2
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/predefined-dashboards:/predefined-dashboards
    ports:
      - "3000:3000"
    networks:
      - minitwit_network

networks:
  minitwit_network:
    driver: bridge

volumes:
  pg_data:
  grafana-data:
