version: "3.8" # version to be compatible with docker swarm/stack deployments

services:
  test:
    build: .
    container_name: minitwit
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4567:4567"
    networks:
      - minitwit_network_test
    command: ["rspec"]
    env_file:
      - .env.test

  db:
    image: postgres:15
    container_name: minitwit_test_db
    restart: always
    env_file:
      - .env.test
    expose:
      - "5432"
    networks:
      - minitwit_network_test
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  minitwit_network_test:
    driver: bridge

volumes:
  pg_data:
