global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'minitwit-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'itu-minitwit-app'

    static_configs:
      - targets: ['web:4567']
      