version: '3.8' # version to be compatible with docker swarm/stack deployments

services:

  db:
    image: postgres:15
    deploy:
      mode: global # global mode to ensure one instance of the services is deployed
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          # - "node.hostname==minitwit.manager"
          - "node.role==manager"
    environment:
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg_data:/var/lib/postgresql/data

secrets:
  POSTGRES_DB:
    external: true 
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true



volumes:
  pg_data:
