version: "3.8"

services:
  web:
    image: registry.digitalocean.com/sad-containers/minitwit:${TAG}
    deploy:
      replicas: 2
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    env_file:
      - .env
    ports:
      - "4567:4567"

  db:
    image: postgres:15
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  prometheus:
    image: registry.digitalocean.com/sad-containers/prometheus:${TAG}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - prometheus-data:/prometheus

  grafana:
    image: registry.digitalocean.com/sad-containers/grafana:${TAG}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    env_file:
      - .env
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"

  elasticsearch-setup:
    image: registry.digitalocean.com/sad-containers/elasticsearch-setup:${TAG}
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: none
    env_file:
      - .env
    volumes:
      - elasticsearch-init:/data

  elasticsearch:
    image: registry.digitalocean.com/sad-containers/elasticsearch:${TAG}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    environment:
      node.name: elasticsearch
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    env_file:
      - .env
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data:Z

  logstash:
    image: registry.digitalocean.com/sad-containers/logstash:${TAG}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    env_file:
      - .env

  kibana:
    image: registry.digitalocean.com/sad-containers/kibana:${TAG}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "5601:5601"
    env_file:
      - .env

  filebeat:
    image: registry.digitalocean.com/sad-containers/filebeat:${TAG}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    user: root
    command:
      - -e
      - --strict.perms=false
    env_file:
      - .env
    volumes:
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

volumes:
  pg_data:
  prometheus-data:
  grafana-data:
  elasticsearch-data:
  elasticsearch-init:
