version: "3.8"

services:
  web:
    image: registry.digitalocean.com/sad-containers/minitwit:${TAG}
    deploy:
      replicas: 2
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 250m
    env_file:
      - .env
    ports:
      - "4567:4567"
    networks:
      - minitwit_network

  db:
    image: postgres:15
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 250m
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - minitwit_network

  backup:
    image: eeshugerman/postgres-backup-s3:15
    env_file:
      - .env
    networks:
      - minitwit_network
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"

  prometheus:
    image: registry.digitalocean.com/sad-containers/prometheus:${TAG}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 250m
    volumes:
      - prometheus-data:/prometheus
    networks:
      - minitwit_network

  grafana:
    image: registry.digitalocean.com/sad-containers/grafana:${TAG}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 250m
    env_file:
      - .env
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - minitwit_network

  elasticsearch-setup:
    image: registry.digitalocean.com/sad-containers/elasticsearch-setup:${TAG}
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: none
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 250m
    env_file:
      - .env
    volumes:
      - elasticsearch-init:/data
    networks:
      - minitwit_network

  elasticsearch:
    image: registry.digitalocean.com/sad-containers/elasticsearch:${TAG}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 250m
    environment:
      node.name: elasticsearch
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    env_file:
      - .env
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data:Z
    networks:
      - minitwit_network

  logstash:
    image: registry.digitalocean.com/sad-containers/logstash:${TAG}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 250m
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    env_file:
      - .env
    networks:
      - minitwit_network

  kibana:
    image: registry.digitalocean.com/sad-containers/kibana:${TAG}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "5601:5601"
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 250m
    env_file:
      - .env
    networks:
      - minitwit_network

  filebeat:
    image: registry.digitalocean.com/sad-containers/filebeat:${TAG}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      placement:
        constraints:
          - "node.role==manager"
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: 250m
    user: root
    command:
      - -e
      - --strict.perms=false
    env_file:
      - .env
    volumes:
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - minitwit_network

volumes:
  pg_data:
  prometheus-data:
  grafana-data:
  elasticsearch-data:
  elasticsearch-init:

networks:
  minitwit_network:
    driver: overlay
