apiVersion: 1
datasources:
  - name: "postgresql"
    type: "postgres"
    url: "db:5432"
    user: $__env{GF_POSTGRES_USERNAME}
    secureJsonData:
      password: $__env{GF_POSTGRES_PASSWORD}
    jsonData:
      database: "minitwit"
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: true