{
 "title": "Minitwit Dashboard",
 "tags": [
  "http",
  "server",
  "requests",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HTTP response count by status codes",
   "type": "timeseries",
   "description": "Shows the number of HTTP responses during the last minute at any given point of the time range, grouped by status codes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_total[1m])) by (code) > 0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HTTP error response count",
   "type": "timeseries",
   "description": "Shows the number of HTTP client- and server-side error responses during the last minute at any given point of the time range.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n    label_replace(\n        sum(increase(http_server_requests_total{code=~\"4..\"}[1m])) by (code)\n            or on() vector(0),\n        \"error_category\",\n        \"4xx - Client error\",\n        \"code\",\n        \".*\"\n    )\n) by (error_category)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        sum(increase(http_server_requests_total{code=~\"5..\"}[1m])) by (code)\n            or on() vector(0),\n        \"error_category\",\n        \"5xx - Server error\",\n        \"code\",\n        \".*\"\n    )\n) by (error_category)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency percentiles",
   "type": "timeseries",
   "description": "Shows the median, 95th and 99th percentiles of latency (request duration) in milliseconds at any given point of the time range.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(increase(http_server_request_duration_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(http_server_request_duration_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(http_server_request_duration_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "gauge",
   "description": "Shows the average latency in milliseconds over the given time range.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_sum[$__range]) or on() vector(0))\n    / clamp_min(sum(increase(http_server_request_duration_seconds_count[$__range]) or on() vector(0)), 1)\n    * 1000",
     "legendFormat": "Average latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(http_server_request_duration_seconds_bucket[$__range])) by (le)) \n    * 1000",
     "legendFormat": "Max latency"
    }
   ]
  },
  {
   "title": "Total registered users",
   "type": "stat",
   "description": "Shows the total number of registerd users in the Minitwit application.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from \"user\""
    }
   ]
  }
 ]
}