---
name: Continuous Deployment Staging

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - develop
      - swarm
      - swarm-logging-fix


# env variables
env:
  DROPLET_NAME: "minitwit-staging"
  REGISTRY_NAME: "registry.digitalocean.com/sad-containers"
  SSH_USER: "root"
  SSH_HOST: "157.245.22.36" # refers to the reserved IP address of the droplet

# I've split the workflow into three jobs: build_and_push, test, and deploy.
# The three jobs makes it easy to see which part fails in the Github Actions UI.

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: docker compose -f docker-compose.testing.yml up --abort-on-container-exit --exit-code-from test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      # check rate limit for digital ocean
      - name: Check rate limit
        run: doctl account ratelimit --format Remaining

      # BUILD AND PUSH MINITWIT IMAGE
      - name: Build minitwit container image
        run: docker build -t ${{ env.REGISTRY_NAME }}/minitwit:latest .
      - name: Push minitwit image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/minitwit:latest

      # BUILD AND PUSH PROMETHEUS IMAGE
      - name: Build prometheus container image
        run: docker build -t ${{ env.REGISTRY_NAME }}/prometheus:latest ./prometheus
      - name: Push prometheus image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/prometheus:latest

      # BUILD AND PUSH GRAFANA IMAGE
      - name: Build grafana container image
        run: docker build -t ${{ env.REGISTRY_NAME }}/grafana:latest ./grafana
      - name: Push grafana image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/grafana:latest

      # BUILD AND PUSH FILEBEAT IMAGE
      - name: Build filebeat container image
        run: docker build -t ${{ env.REGISTRY_NAME }}/filebeat:latest ./elk/filebeat
      - name: Push filebeat image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/filebeat:latest

      # BUILD AND PUSH LOGSTASH IMAGE
      - name: Build logstash container image
        run: docker build -t ${{ env.REGISTRY_NAME }}/logstash:latest ./elk/logstash
      - name: Push logstash image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/logstash:latest
      
      # BUILD AND PUSH ELASTICSEARCH SETUP IMAGE
      - name: Build elasticsearch setup container image
        run: docker build -t ${{ env.REGISTRY_NAME }}/elasticsearch-setup:latest ./elk/elasticsearch/setup
      - name: Push elasticsearch setup image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/elasticsearch-setup:latest

      # BUILD AND PUSH ELASTICSEARCH IMAGE
      - name: Build elasticsearch container image
        run: docker build -t ${{ env.REGISTRY_NAME }}/elasticsearch:latest ./elk/elasticsearch
      - name: Push elasticsearch image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/elasticsearch:latest

      # BUILD AND PUSH KIBANA IMAGE
      - name: Build kibana container image
        run: docker build -t ${{ env.REGISTRY_NAME }}/kibana:latest ./elk/kibana
      - name: Push kibana image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/kibana:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        # Configure the ~./bash_profile and deploy.sh file on the Vagrantfile
        run: >
          ssh $SSH_USER@$SSH_HOST
          -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no
          'cd /minitwit; ./deploy.sh'
        env:
          SSH_USER: ${{ env.SSH_USER }}
          SSH_HOST: ${{ env.SSH_HOST }}
