---
name: Generate Report

on:
  push:
    # Run workflow every time something is pushed to the develop branch
    branches:
      - main
    paths:
      - "report/**.md"
      - "report/images/**"

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge files
        run: |
          mkdir -p report/tmp
          mkdir -p report/build
          find report -maxdepth 1 -name "*.md" | sort | while read file; do
            cat "$file"
            echo ""
          done > "report/tmp/report.md"

      - name: Markdown to PDF and HTML
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: report/tmp/report.md
          images_dir: report/images
          image_import: ./images
          output_path: report/build
          build_pdf: true
          build_html: false

      - name: Commit and push generated report
        run: |
          ls -la report
          ls -la report/build
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A report/build/report.md
          git commit -m "Auto-generate report PDF" || echo "No changes to commit"
          git push
