---
name: Test merged workflows

on:
  push:
    branches:
      - 162-merge-workflows-build-and-test

# env variables
env:
  DROPLET_NAME: "minitwit"
  REGISTRY_NAME: "registry.digitalocean.com/sad-containers"
  SSH_USER: "root"
  SSH_HOST: "209.38.114.92"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Build container image
        run: docker build -t ${{ env.REGISTRY_NAME }}/minitwit:processing .

      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/minitwit:processing

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Setup environment variables
        run: cp .env.test .env

      - name: Run Ruby Tests
        run: |
          docker compose -f docker-compose.test-github.yml run web rspec

      - name: Setup E2E Environment
        run: |
          docker compose -f docker-compose.test-github.yml up -d
          sudo apt-get update
          sudo apt-get install -y python3
          pip install -r simulator/requirements.txt -r requirements.txt

      - name: Install browser for E2E
        run: python3 -m playwright install --with-deps

      - name: Run your E2E tests
        run: pytest --tracing=retain-on-failure

      - name: Setup Simulator Environment
        run: |
          docker compose -f docker-compose.test-github.yml up -d

      - name: Run Simulator tests
        run: |
          cd simulator
            python3 minitwit_simulator_test.py http://0.0.0.0:4567 || (docker logs minitwit && exit 1)
