---
name: Test merged workflows

on:
  push:
    branches:
      - 162-merge-workflows-build-and-test

# env variables
env:
  DROPLET_NAME: "minitwit"
  REGISTRY_NAME: "registry.digitalocean.com/sad-containers"
  SSH_USER: "root"
  SSH_HOST: "209.38.114.92"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build container image
        run: docker build -t ${{ env.REGISTRY_NAME }}/minitwit:latest .

      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ env.REGISTRY_NAME }}/minitwit:latest

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file based on example
        run: cp .env.test .env

      - name: Setup project
        run: docker compose -f docker-compose.test-deploy.yml up

      - name: Install python
        run: sudo apt-get update && sudo apt-get install -y python3

      - name: Install dependencies
        run: pip install -r simulator/requirements.txt

      - name: Wait for web service to be ready
        run: |
          echo "Waiting for web service"
          for i in {1..100}; do
            if curl -s http://0.0.0.0:4567 > /dev/null; then
              echo "Web service is ready"
              exit 0
            fi
            echo -n "."
            sleep 0.1
          done
          echo "Web service did not become ready in time"
          docker logs minitwit
          exit 1

      - name: Run tests
        run: |
          cd simulator
            python3 minitwit_simulator_test.py http://0.0.0.0:4567 || (docker logs minitwit && exit 1)
