# based on script from https://playwright.dev/python/docs/ci-intro
name: Playwright Tests
on:
  pull_request:
    branches:
        - '*' # all branches

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file based on example
      run: cp .env.example .env

    - name: Start Docker Compose
      run: docker compose -f docker-compose.dev.yml up --detach --remove-orphans

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    - name: Wait for services to be ready
      run: |
          until curl -s http://localhost:4567/health | grep "OK"; do
            echo "Waiting for services to be ready..."
            sleep 5
          done
      
    - name: Run your tests
      run: |
       cd Playwright
       pytest --tracing=retain-on-failure

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/