---
name: Pull Request Test

on:
  pull_request:
    # Run workflow every time something is in a pull request
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment variables
        run: cp .env.test .env

      - name: Run Ruby Tests
        run: |
          docker compose -f docker-compose.testing.yml

      - name: Setup Simulator Environment
        run: |
          docker compose -f docker-compose.testing.yml run web "ruby minitwit.rb" -d
          sudo apt-get update
          sudo apt-get install -y python3
          pip install -r requirements.txt

      - name: Run Simulator tests
        run: |
          cd simulator
            python3 minitwit_simulator_test.py http://0.0.0.0:4567 || (docker logs minitwit && exit 1)
