---
name: Pull Request Test

on:
  pull_request:
    # Run workflow every time something is in a pull request
    branches:
      - '*' # all branches

# env variables
env:
  DROPLET_NAME: "minitwit"
  REGISTRY_NAME: "registry.digitalocean.com/sad-containers"
  SSH_USER: "root"
  SSH_HOST: "209.38.114.92" # refers to the reserved IP address of the droplet

# I've split the workflow into three jobs: build_and_push, test, and deploy.
# The three jobs makes it easy to see which part fails in the Github Actions UI.

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: docker compose -f docker-compose.testing.yml up --abort-on-container-exit --exit-code-from test
