---
name: Test using simulator

on:
  pull_request:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
      - develop

# env variables
env:
  DROPLET_NAME: "minitwit"
  REGISTRY_NAME: "registry.digitalocean.com/sad-containers"
  SSH_USER: "root"
  SSH_HOST: "209.38.114.92" # refers to the reserved IP address of the droplet

# I've split the workflow into three jobs: build_and_push, test, and deploy.
# The three jobs makes it easy to see which part fails in the Github Actions UI.

jobs:
  test_simulator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file based on example
        run: cp .env.test .env

      - name: Setup project
        run: docker compose up -d

      - name: Install python
        run: sudo apt-get update && sudo apt-get install -y python3

      - name: Install dependencies
        run: pip install -r simulator/requirements.txt

      - name: Wait for web service to be ready
        run: |
          echo "Waiting for web service"
          for i in {1..100}; do
            if curl -s http://0.0.0.0:4567 > /dev/null; then
              echo "Web service is ready"
              exit 0
            fi
            echo -n "."
            sleep 0.1
          done
          echo "Web service did not become ready in time"
          docker logs minitwit
          exit 1

      - name: Run tests
        run: |
          cd simulator
            python3 minitwit_simulator_test.py http://0.0.0.0:4567 || (docker logs minitwit && exit 1)
